### ISSUE TITLE
[Ops] 개발망 Kubernetes 인프라 구축

### ISSUE THREAD

**Issue by robert-min** [FLYAI4/ArtInfra-k8s#1]
### 📌 Description

서버 배포, 인프라 구축을 위해 개발망 Kubernetes 인프라를 구축합니다.

<br>

### 🎈 Goal
<p>$\tiny{구체적인\ 산출물을\ 포함한\ 목표를\ 작성해주세요.}$</p>

- 서버 비용을 고려하여 로컬 데스크탑을 활용해 인프라 구성
- 원격 데스크탑으로 인프라 관리 가능하도록 구성

<br>

### ✏️ Todo
<p>$\tiny{목표\ 달성을\ 위해\ 해야할\ 일을\ 세부적으로\ 작성해주세요.}$</p>

- [x] 로컬 컴퓨터 성능 확인
- [x] 쿠버네티스 인프라 구축
  - [x] Hyper-V 분산 서버 구축
  - [x] 쿠버네티스 설치
  - [x] master-worker 연동
  - [x] 정상 배포 확인
- [x] 원격 접속 테스트

**Comment by robert-min** [comment]
## 기본 배포 스크립트

```yaml
apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
spec:
  selector:
    app: fastapi
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
        - name: fastapi-container
          image: robertmin/art-vision:0.0.0
          ports:
            - containerPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx-container
          image: nginx:latest
          ports:
            - containerPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fastapi-ingress
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: fastapi-service
                port:
                  number: 8000

```
